# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(599, 332)
        Frame.setMinimumSize(QtCore.QSize(599, 332))
        Frame.setMaximumSize(QtCore.QSize(599, 332))
        Frame.setStyleSheet("border:none")
        Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame = QtWidgets.QFrame(parent=Frame)
        self.frame.setGeometry(QtCore.QRect(0, 0, 599, 332))
        self.frame.setMinimumSize(QtCore.QSize(599, 332))
        self.frame.setMaximumSize(QtCore.QSize(599, 332))
        self.frame.setStyleSheet("QFrame{ \n"
"    background-color:rgb(108, 67, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Event_Button = QtWidgets.QPushButton(parent=self.frame)
        self.Event_Button.setGeometry(QtCore.QRect(90, 110, 131, 101))
        self.Event_Button.setMinimumSize(QtCore.QSize(131, 101))
        self.Event_Button.setMaximumSize(QtCore.QSize(131, 101))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.Event_Button.setFont(font)
        self.Event_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.Event_Button.setObjectName("Event_Button")
        self.Dristpunk_Button = QtWidgets.QPushButton(parent=self.frame)
        self.Dristpunk_Button.setGeometry(QtCore.QRect(390, 110, 131, 101))
        self.Dristpunk_Button.setMinimumSize(QtCore.QSize(131, 101))
        self.Dristpunk_Button.setMaximumSize(QtCore.QSize(131, 101))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.Dristpunk_Button.setFont(font)
        self.Dristpunk_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.Dristpunk_Button.setObjectName("Dristpunk_Button")
        self.nicknameEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.nicknameEdit.setGeometry(QtCore.QRect(242, 160, 111, 22))
        self.nicknameEdit.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(240, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.Folder_Button = QtWidgets.QPushButton(parent=self.frame)
        self.Folder_Button.setGeometry(QtCore.QRect(544, 283, 41, 41))
        self.Folder_Button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(129, 80, 0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}\n"
"")
        self.Folder_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("other sources/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Folder_Button.setIcon(icon)
        self.Folder_Button.setIconSize(QtCore.QSize(25, 25))
        self.Folder_Button.setObjectName("Folder_Button")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(260, 187, 81, 81))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.RamButton = QtWidgets.QPushButton(parent=self.frame)
        self.RamButton.setGeometry(QtCore.QRect(14, 283, 41, 41))
        self.RamButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(129, 80, 0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}\n"
"")
        self.RamButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.RamButton.setIcon(icon1)
        self.RamButton.setIconSize(QtCore.QSize(35, 35))
        self.RamButton.setObjectName("RamButton")
        self.ApplyNicknameButton = QtWidgets.QPushButton(parent=self.frame)
        self.ApplyNicknameButton.setGeometry(QtCore.QRect(360, 160, 21, 21))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(10)
        self.ApplyNicknameButton.setFont(font)
        self.ApplyNicknameButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(139, 139, 139);\n"
"}\n"
"")
        self.ApplyNicknameButton.setObjectName("ApplyNicknameButton")
        self.UpdateAllEvent_Button = QtWidgets.QPushButton(parent=self.frame)
        self.UpdateAllEvent_Button.setGeometry(QtCore.QRect(90, 220, 131, 21))
        self.UpdateAllEvent_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.UpdateAllEvent_Button.setMaximumSize(QtCore.QSize(99999, 9999))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.UpdateAllEvent_Button.setFont(font)
        self.UpdateAllEvent_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.UpdateAllEvent_Button.setObjectName("UpdateAllEvent_Button")
        self.UpdateModsEvent_Button = QtWidgets.QPushButton(parent=self.frame)
        self.UpdateModsEvent_Button.setGeometry(QtCore.QRect(90, 250, 131, 21))
        self.UpdateModsEvent_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.UpdateModsEvent_Button.setMaximumSize(QtCore.QSize(99999, 9999))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.UpdateModsEvent_Button.setFont(font)
        self.UpdateModsEvent_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.UpdateModsEvent_Button.setObjectName("UpdateModsEvent_Button")
        self.UpdateAllDristpunk_Button = QtWidgets.QPushButton(parent=self.frame)
        self.UpdateAllDristpunk_Button.setGeometry(QtCore.QRect(390, 220, 131, 21))
        self.UpdateAllDristpunk_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.UpdateAllDristpunk_Button.setMaximumSize(QtCore.QSize(99999, 9999))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.UpdateAllDristpunk_Button.setFont(font)
        self.UpdateAllDristpunk_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.UpdateAllDristpunk_Button.setObjectName("UpdateAllDristpunk_Button")
        self.UpdateModsDristpunk_Button = QtWidgets.QPushButton(parent=self.frame)
        self.UpdateModsDristpunk_Button.setGeometry(QtCore.QRect(390, 250, 131, 21))
        self.UpdateModsDristpunk_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.UpdateModsDristpunk_Button.setMaximumSize(QtCore.QSize(99999, 9999))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.UpdateModsDristpunk_Button.setFont(font)
        self.UpdateModsDristpunk_Button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(129, 80, 0);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.UpdateModsDristpunk_Button.setObjectName("UpdateModsDristpunk_Button")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 320, 61, 16))
        self.label_3.setStyleSheet("background-color: none")
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 601, 41))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 261, 31))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.minButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.minButton.setGeometry(QtCore.QRect(519, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.minButton.setFont(font)
        self.minButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.closeButton.setGeometry(QtCore.QRect(560, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("ascii")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:rgb(162, 100, 0);\n"
"}")
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "DristLauncher"))
        self.Event_Button.setText(_translate("Frame", "Ивент"))
        self.Dristpunk_Button.setText(_translate("Frame", "DristPunk3"))
        self.label.setText(_translate("Frame", "NickName:"))
        self.ApplyNicknameButton.setText(_translate("Frame", "Ok"))
        self.UpdateAllEvent_Button.setText(_translate("Frame", "Update All"))
        self.UpdateModsEvent_Button.setText(_translate("Frame", "Update Mods"))
        self.UpdateAllDristpunk_Button.setText(_translate("Frame", "Update All"))
        self.UpdateModsDristpunk_Button.setText(_translate("Frame", "Update Mods"))
        self.label_3.setText(_translate("Frame", "alpha-0.0.2"))
        self.label_2.setText(_translate("Frame", "DristLauncher"))
        self.minButton.setText(_translate("Frame", "-"))
        self.closeButton.setText(_translate("Frame", "🞪"))
