# Form implementation generated from reading ui file 'ram_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RamFrame(object):
    def setupUi(self, RamFrame):
        RamFrame.setObjectName("RamFrame")
        RamFrame.resize(404, 104)
        RamFrame.setStyleSheet("QFrame{\n"
"    background-color:rgb(108, 67, 0);\n"
"}")
        self.widget = QtWidgets.QWidget(parent=RamFrame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 41))
        self.widget.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(149, 92, 0)")
        self.widget.setObjectName("widget")
        self.RamSlider = QtWidgets.QSlider(parent=self.widget)
        self.RamSlider.setGeometry(QtCore.QRect(10, 10, 361, 21))
        self.RamSlider.setSingleStep(100)
        self.RamSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.RamSlider.setObjectName("RamSlider")
        self.widget_2 = QtWidgets.QWidget(parent=RamFrame)
        self.widget_2.setGeometry(QtCore.QRect(140, 40, 120, 51))
        self.widget_2.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(149, 92, 0);\n"
"border:none;\n"
"color:white")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(8, 9, 51, 31))
        self.label.setObjectName("label")
        self.RamEditLine = QtWidgets.QLineEdit(parent=self.widget_2)
        self.RamEditLine.setGeometry(QtCore.QRect(40, 11, 71, 31))
        self.RamEditLine.setStyleSheet("background-color:rgb(202, 125, 0)")
        self.RamEditLine.setObjectName("RamEditLine")
        self.pushButton = QtWidgets.QPushButton(parent=RamFrame)
        self.pushButton.setGeometry(QtCore.QRect(274, 60, 101, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(RamFrame)
        QtCore.QMetaObject.connectSlotsByName(RamFrame)

    def retranslateUi(self, RamFrame):
        _translate = QtCore.QCoreApplication.translate
        RamFrame.setWindowTitle(_translate("RamFrame", "Ram Edit"))
        self.label.setText(_translate("RamFrame", "RAM:"))
        self.RamEditLine.setText(_translate("RamFrame", "6000"))
        self.pushButton.setText(_translate("RamFrame", "Apply"))
